### PR TITLE
issue 105 overall ui ux improvements

### PR DESCRIPTION
**Pull request by jmastr**

### CODE REVIEW

**Comment by micuintus** [comment]
Thanks a lot! Very nice!
A few comments/questions:
1. I **really** like the line below the search bar and below the venue details!
2. Is it possible that design of the street label when flicking the venue description up is a bit strange? Take for example "Viasko", if you flick it up, a small rectangle gets more and more opaque, which imo looks a bit weird. What do you think?
3. Is it possible that you forgot to set ```BVApp.Theme.dividerColor``` on SailfishOS?
4. Using only the gray color in the list for everything looks a bit … pale … imo. I know that this comes from the designer, but I am not too sure about that atm (especially on SailfishOS it looks weird, maybe we should at least find a special case solution for SailfishOS here!?)

Good job, buddy, really nice!

**Comment by jmastr** [comment]
> 1. I really like the line below the search bar and below the venue details!
Me too!
> 2. Is it possible that design of the street label when flicking the venue description up is a bit strange? Take for example "Viasko", if you flick it up, a small rectangle gets more and more opaque, which imo looks a bit weird. What do you think?
Yea, this is a know issue. I know the reason for that as well, but I would like to address that in another ticket. There need to be a follow up ticket anyways, because we don't know, what to do, if a venue has no picture.
> 3. Is it possible that you forgot to set BVApp.Theme.dividerColor on SailfishOS?
Naaaaa, it is there: qml/components-Sailfish/Theme.qml#L63 in my PR
> 4. Using only the gray color in the list for everything looks a bit … pale … imo. I know that this comes from the designer, but I am not too sure about that atm (especially on SailfishOS it looks weird, maybe we should at least find a special case solution for SailfishOS here!?)
I like the design on v-play, because it is aligned with the current Android app, but I can do an exception for Sailfish. I will update my PR.

**Comment by jmastr** [comment]
Okay, my fault:

`[W] unknown:63 - qrc:///imports/BerlinVegan/components/platform/Theme.qml:63:41: Unable to assign QColor to int`

**Comment by micuintus** [comment]
FERI NISHE!

**Pull request merged**
