### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:)

### CODE REVIEW

**Comment by micuintus** [comment]
This is soooo cool, it absolutely made my day: A Dutch translation for a Berlin vegan guide! :dancing_men: 
Thank you very much!

I filed a small PR to your branch, which adds the translations to the resources.

**Comment by micuintus** [comment]
Another minor thing: Our German translation for "closed now" is just "geschlossen", because "momentan geschlossen" takes quite some place. You might want to do the same for the Dutch translation:

screenshot_20180618_132454

**Comment by Vistaus** [comment]
You're very welcome! Happy to hear that it made your day! :smile_cat: 

You're absolutely right about the translation for "closed now". I'll change that.

**Comment by Vistaus** [comment]
Done!

**Comment by micuintus** [comment]
Cool, thanks. Please also merge my PR to your branch (or commit the same changes yourself), otherweise the Dutch translation doesn't work.

**Comment by Vistaus** [comment]
Sorry, I totally forgot to that! It's been merged now.

**Comment by micuintus** [comment]
So cool, thank you!

**Comment by Vistaus** [comment]
You're welcome! :)

**Pull request merged**
