### PR TITLE
117 change the get directions icon

### PR DESCRIPTION
**Pull request by jmastr**

### CODE REVIEW

**Comment by jmastr** [comment]
I am not sure about the size of the directions icon. Is it too big?

**Comment by micuintus** [comment]
> I am not sure about the size of the directions icon. Is it too big?

Me neither, I have to sleep over it ;)

**Comment by micuintus** [comment]
> I am not sure about the size of the directions icon. Is it too big?

Yes, after I slept over it, I actually do think it is too big. I'll merge it and will send you a PR
with suggestion in a few secs.

**Comment by micuintus** [comment]
Nice work BTW!

**Pull request merged**
