### PR TITLE
Micu/icon sizes

### PR DESCRIPTION
**Pull request by micuintus**

### CODE REVIEW

**Comment by micuintus** [comment]
Before:
before

After:
after

**Comment by micuintus** [comment]
BTW: The size of the directions icon and the icon tool bar icons is 26 after this PR.
I'd also be down with going for 27 or 28.

This is how it looks with 28:

with28

**Comment by micuintus** [comment]
This is with 27, actually, after looking at the three of them, I think 27 might be the best choice, @jmastr, what do you think?


with27

**Comment by jmastr** [comment]
@micuintus i like 28 for the directions-icon

**Comment by jmastr** [comment]
Perfect. Thanks!

**Pull request merged**
