### PR TITLE
Micu/issue#31 filter

### PR DESCRIPTION
**Pull request by micuintus**
Part 1 (next part will follow in another PR): 
* Filter by vegetarian/vegan category
* Filter by venue properties

Still missing: 
* Filter by food category (café, fast food, ice cream etc.)
* Move Shopping/Food to filter
* Code still a bit messy

Known issue:
* Filter should not be applied to favorites

### CODE REVIEW

**Comment by jmastr** [comment]
> Filter should not be applied to favorites

Why not? If you want to filter your favs?!

**Comment by micuintus** [comment]
> > Filter should not be applied to favorites
> Why not? If you want to filter your favs?!

It just felt weird for me that I changed the filter settings and some of my favs were gone. My assumption is that some users wouldn't expect that. Plus: Normally you only have a few favs where pure string search is enough. But I am by no means am not settled on that.

**Comment by jmastr** [comment]
c48765f does not work as aspected for me: `IconType.leaf` is not rendered properly, but just a green rectangle.

**Comment by jmastr** [comment]
Nice one! Works as advertised!

**Pull request merged**
